# Generated by Django 4.2.17 on 2024-12-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(),
        ),
    ]
